AllCops:
  DisplayCopNames: true
  Exclude:
    - '**/db/**'
    - '**/bin/spring'
Rails:
  Enabled: true
Documentation:
  Enabled: false
Metrics/ClassLength:
  Exclude:
    - '**/spec/**/*spec.rb'
Metrics/AbcSize:
  Exclude:
    - '**/spec/**/*spec.rb'
  Max: 30
Metrics/MethodLength:
  Exclude:
    - '**/spec/**/*spec.rb'
  Max: 18
Metrics/LineLength:
  Exclude:
    - '**/config/**/*.rb'
    - '**/db/seeds.rb'
Style/ClassAndModuleChildren:
  Enabled: false
Style/BlockComments:
  Enabled: false