AllCops:
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - '**/bin/spring'
    - 'config/**/*'
    - 'Guardfile'
    - 'spec/i18n_spec.rb'
Rails:
  Enabled: true
Documentation:
  Enabled: false
Metrics/ClassLength:
  Exclude:
    - '**/spec/**/*spec.rb'
Metrics/AbcSize:
  Exclude:
    - '**/spec/**/*spec.rb'
  Max: 30
Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*spec.rb'
Metrics/MethodLength:
  Exclude:
    - '**/spec/**/*spec.rb'
  Max: 18
Metrics/LineLength:
  Exclude:
    - '**/config/**/*.rb'
    - '**/db/seeds.rb'
  Max: 120
Style/ClassAndModuleChildren:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/TrailingCommaInLiteral:
  Enabled: false
