inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - 'vendor/**/*'
Rails:
  Enabled: true

Style/TrailingCommaInLiteral:
  Enabled: false